image: python:3.8

services:
  - postgres:11.2-alpine
  - mongo:4.0.9-xenial

variables:
  POSTGRES_DB: spinta
  POSTGRES_USER: ci
  POSTGRES_PASSWORD: secret

cache:
  paths:
    - ~/.cache/pip/

before_script:
  - python --version
  - pip install poetry
  - poetry --version
  - poetry config virtualenvs.in-project true
  # FIXME: https://setuptools.readthedocs.io/en/latest/history.html#v58-0-0
  #        simpleeval package uses use_2to3 thus it is not compatbile with
  #        setuptools>=58
  #        See: https://github.com/python-poetry/poetry/issues/4511
  - poetry config experimental.new-installer false
  - poetry run pip install 'setuptools==57.5.0'
  - poetry install -vv

test:
  variables:
    SPINTA_BACKENDS__DEFAULT__DSN: postgresql://ci:secret@postgres:5432/spinta
    SPINTA_BACKENDS__MONGO__DSN: mongodb://mongo/
  script:
    - >-
      poetry run py.test -vvxra --tb=native \
        --log-level=debug \
        --cov=spinta \
        --cov-report=term-missing \
        tests
