dist: xenial
language: python
python: 3.7
env:
  - PATH=$HOME/.poetry/bin:$PATH
before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
install:
  - poetry install
script:
  - poetry run py.test -vvra --tb=native --cov-report=term-missing --cov=spinta tests
