dist: xenial
language: python
python: 3.7

services:
  - postgresql

env:
  - SPINTA_TEST_DATABASE=postgresql://localhost/spinta

install:
  - pip install -r requirements-dev.txt -e .

before_script:
  - psql -c 'create database spinta;' -U postgres

script:
  - py.test -vvra --tb=native --cov-report=term-missing --cov=spinta tests

after_script:
  - codecov
