version: "3"

services:
    db:
        image: postgres:11.2-alpine
        ports:
            - "5432"
        environment:
            - POSTGRES_DB=spinta
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin123
        volumes:
            - "./postgres-data:/var/lib/postgresql/data"
    app:
        build: .
        ports:
            - "8000:8000"
        environment:
            - SPINTA_BACKENDS_DEFAULT_DSN=postgresql://admin:admin123@db:5432/spinta
            - SPINTA_MANIFESTS_DEFAULT_PATH=tests/manifest
            - SPINTA_TEST_DATABASE_DSN=postgresql://admin:admin123@db:5432/spinta_tests
        depends_on:
            - db
        volumes:
            - ".:/opt/spinta"
        stdin_open: true
        tty: true
