version: "3"

services:
  db:
    image: postgis/postgis:16-3.4
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_DB=spinta
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    volumes:
      - postgres:/var/lib/postgresql/data
  mongo:
    image: mongo:4.0.9-xenial
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=spinta
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    volumes:
      - mongo:/data/db
  app:
    volumes:
      - ./entrypoint.sh:/app/entrypoint.sh
    image: spinta:local
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - ./entrypoint.sh
    environment:
      - SPINTA_CONFIG=config.yml  # TODO update actual keymap, using notes/spinta/server.sh keymap for now.
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongo

  redis-keymap: # sqlite faster alternative
    image: valkey/valkey:9
    restart: always
    command: [ "redis-server", "--appendonly", "yes" ] # persistence settings to persist always, without any data loss.
    volumes:
      - redis_keymap_data:/data
    ports:
      - "6379:6379"
volumes:
  postgres:
  mongo:
  redis_keymap_data:
