[tool.poetry]
name = "spinta"
version = "0.1.0"
description = ""
authors = ["Mantas <sirexas@gmail.com>"]
license = "MIT"
packages = [
    {include = "spinta"},
]

[tool.poetry.dependencies]
python = "^3.7"
sanic = "^18.12"
asyncpg = "^0.18.3"
"ruamel.yaml" = "^0.15.87"
setuptools = "^40.7"
sqlalchemy = "^1.2"
psycopg2-binary = "^2.7"
unidecode = "^1.0"

[tool.poetry.dev-dependencies]
pytest = "^4.1"
pprintpp = "^0.4.0"
pp-ez = "^0.2.0"
pytest-mock = "^1.10"
sqlalchemy-utils = "^0.33.11"
responses = "^0.10.5"
toposort = "^1.5"
pytest-cov = "^2.6"
codecov = "^2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
