name: 'Run code linter'

on:
  push:
    branches: [master, "[0-9]+.[0-9]+"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry --version
          poetry install --all-extras -vv

      - name: Run ruff check
        run: poetry run ruff check .
